### PR TITLE
lxqt-config: Load/store window size on begin/end

### PR DESCRIPTION
**Pull request by palinek**
closes lxde/lxqt#406

### CODE REVIEW

**Comment by paulolieuthier** [comment]
GTM.

**Comment by pmattern** [comment]
Window does remember its size once the latter got changed but upon start on a new user profile the window looks like this here
lxqt-config_window-size_first-launch

**Comment by tsujan** [comment]
`QSettings::value()` (and perhaps, `QSettings::setValue()`) needs a reasonable fallback.

**Comment by palinek** [comment]
@pmattern tried to fix in @790b577. Is it now OK?

**Comment by pmattern** [comment]
As of 790b577 the size of the window of `lxqt-config` gets remembered, upon first start on a new user profile section "System settings" is still cut almost completely due to the window's small height.

Don't know whether the latter is something that really needs to get changed and tend to say no.
When parts of the window don't get displayed as its height is too low there's a scroll bar very well visible at the right edge. This plus the fact that changed window sizes do get remembered now should actually do, IMO.
Also, I wonder whether enforcing a larger height from the very beginning could eventually cause problems on rather tiny displays.

**Comment by palinek** [comment]
> Don't know whether the latter is something that really needs to get changed and tend to say no.
When parts of the window don't get displayed as its height is too low there's a scroll bar very well visible at the right edge. This plus the fact that changed window sizes do get remembered now should actually do, IMO.
Also, I wonder whether enforcing a larger height from the very beginning could eventually cause problems on rather tiny displays.

Then, should we merge this? (I would say yes)

**Comment by agaida** [comment]
I would suggest to ship it

**Comment by palinek** [comment]
done

**Pull request merged**
