### PR TITLE
fr_FR translations for lxqt-config menu entries

### PR DESCRIPTION
**Pull request by ioO**
Modify and add translation files '.desktop' in translation's folder for fr_FR lang.

### CODE REVIEW

**Comment by pmattern** [comment]
Not sure whether you're still interested in this PR getting merged after such a long time as it got under the radar for whatever reason.

If so, two things have to be changed:
* As long as only a single translation of a particular language exists we don't handle it as country-specific. Read, `fr_FR` has to be replaced with `fr` only everywhere.   
Background is explained in the GitHub wiki in [Language vs. country specific translations](https://github.com/lxde/lxqt/wiki/Translation#language-vs-country-specific-translations) (refers to the Qt TS files but applies to the desktop entry files as well).
* The commits have to be squashed into a single one to avoid clutter in the commit history. Right now the number of commits exceeds the one of files that were changed.

That aside the desktop entry file of lxqt-config-brightness was complemented with keys `GenericName` and `Comment` in the meantime so you may want to translate these, too.

**Comment by ioO** [comment]
I think we can close the PR. I will follow your requirements and do a new one. I did a search how to squash commits, it seems to be done with git rebase -i sha1. Is it the good way ? Thanks

**Comment by pmattern** [comment]
Of course you could just close this commit and open a new one, but closing a PR that's basically valid just due to technical issues actually doesn't make too much sense. Also, fixing based upon your current clone may not be much more work than starting over.

So you may want to have a look at the following steps:
To squash run `git rebase -i HEAD~5`. An editor will be opened representing commits and actions to apply in the first column. In lines 6-11 replace "pick" with "squash". This will squash these commits into the one in line 5. Exit the editor saving the file to trigger the action.
Another editor instance will come up were you can edit the commit message of the resulting commit, presenting the messages of all the squashed commits. Condense all those commits into a single reasonable one like "Desktop entry files: Update French translation". Exit saving the file again. Running `git log` shows that all commits in question were squashed into a single one.

**Comment by ioO** [comment]
Thank you for your help and support, I did my homework :-)

**Comment by palinek** [comment]
You're working on a realy outdated version ov lxqt-config here. The \*.ts files aren't handled by specific repositories but moved into a central [lxde/lxqt-l10n](/lxde/lxqt-l10n) repo. So please, rebase to current lxde:master...

**Comment by pmattern** [comment]
This is true but on the other hand there's only a single TS file involved right now which was updated by another contributor in lxde/lxqt-l10n@51c802a meanwhile anyway. There are no merge conflicts affecting the `*.desktop` files which remain.
So I'd suggest to simply drop the TS file from the current commit which has to be done in two steps as it was renamed.
```
$ git rm lxqt-config-appearance/translations/lxqt-config-appearance_fr.ts
$ git checkout e4304b2 lxqt-config-appearance/translations/lxqt-config-appearance_fr_FR.ts
$ git commit --amend
$ git push --force
```

**Comment by ioO** [comment]
I did your suggestions and update the fork for the PR. Thank you @pmattern for your help.

**Comment by pmattern** [comment]
The current changes are exactly what I had in mind, yes.

Meanwhile I stumbled upon another detail which is not bummer but which I'd like to see fixed nevertheless. Could you make sure the three keys are always stated in order `Name` - `GenericName` - `Comment` like it's implemented e. g. in lxqt-config-locale_fr.desktop already?
Should be rather easy. Just edit the files, `git add .`, `git commit --amend` and `git push --force`.

**Comment by ioO** [comment]
Today the --force be with me :)

**Comment by pmattern** [comment]
Everything good to go now, all that's missing is to rebase your elderly master branch against the current one. Just tell us whether we should do it on behalf of you, as said above your authorship would be preserved, or you want to go through the exercise and do it yourself.
If you want to do it yourself it would be good to start by posting the output of `git branch -vv --all`.

**Comment by ioO** [comment]
Sorry for my misunderstanding, I thought I didn't need to rebase. I really appreciate you let me learn and spend time to help me.
Here is the output
```
[ioo@shikoku ~/Projets/lxqt-config]$ git branch -vv --all
* master                           c867147 [origin/master] Desktop entry files: Update French translation
  remotes/origin/HEAD              -> origin/master
  remotes/origin/delay_activation  90930e3 lxqt-config: Avoid multiple spawn on auto-repeat
  remotes/origin/fast-app-chooser  6066964 Delay loading of application icons in the app-chooser dialog for faster loading.
  remotes/origin/master            c867147 Desktop entry files: Update French translation
  remotes/origin/monitor-config    ed84422 Added monitors magnetic attraction in position dialog.
  remotes/origin/switch-to-kscreen 85e49e5 Set mode at session start. Save settings in XDG_CONFIG_HOME (if exists)     or /.config/autostart.
```
I add a remote branch called upstream from lxqt-config.git repo and fetch it
```
[ioo@shikoku ~/Projets/lxqt-config]$ git remote add upstream https://github.com/lxde/lxqt-config.git
[ioo@shikoku ~/Projets/lxqt-config]$ git fetch upstream 
remote: Counting objects: 236, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 236 (delta 120), reused 120 (delta 120), pack-reused 113
Réception d'objets: 100% (236/236), 261.17 KiB | 108.00 KiB/s, fait.
Résolution des deltas: 100% (159/159), complété avec 56 objets locaux.
Depuis https://github.com/lxde/lxqt-config
 * [nouvelle branche] delay_activation      -> upstream/delay_activation
 * [nouvelle branche] fast-app-chooser      -> upstream/fast-app-chooser
 * [nouvelle branche] master                -> upstream/master
 * [nouvelle branche] monitor-config        -> upstream/monitor-config
 * [nouvelle branche] monitor-fast-settings -> upstream/monitor-fast-settings
 * [nouvelle branche] releases-0.11.x       -> upstream/releases-0.11.x
 * [nouvelle branche] set-release           -> upstream/set-release
 * [nouvelle branche] switch-to-kscreen     -> upstream/switch-to-kscreen
 * [nouvelle branche] use-lxqt-build-tools  -> upstream/use-lxqt-build-tools
 * [nouvelle branche] xdgicon_remove        -> upstream/xdgicon_remove
 * [nouvelle étiquette] 0.11.0                -> 0.11.0
```
```
[ioo@shikoku ~/Projets/lxqt-config]$ git branch -vv --all
* master                                 c867147 [origin/master] Desktop entry files: Update French translation
  remotes/origin/HEAD                    -> origin/master
  remotes/origin/delay_activation        90930e3 lxqt-config: Avoid multiple spawn on auto-repeat
  remotes/origin/fast-app-chooser        6066964 Delay loading of application icons in the app-chooser dialog for faster loading.
  remotes/origin/master                  c867147 Desktop entry files: Update French translation
  remotes/origin/monitor-config          ed84422 Added monitors magnetic attraction in position dialog.
  remotes/origin/switch-to-kscreen       85e49e5 Set mode at session start. Save settings in XDG_CONFIG_HOME (if exists)     or /.config/autostart.
  remotes/upstream/delay_activation      47fb40f lxqt-config: Avoid multiple spawn on auto-repeat
  remotes/upstream/fast-app-chooser      6066964 Delay loading of application icons in the app-chooser dialog for faster loading.
  remotes/upstream/master                47fb40f lxqt-config: Avoid multiple spawn on auto-repeat
  remotes/upstream/monitor-config        ed84422 Added monitors magnetic attraction in position dialog.
  remotes/upstream/monitor-fast-settings a2d7cde Merge branch 'master' into monitor-fast-settings
  remotes/upstream/releases-0.11.x       c828d2c Release 0.11.0: Add changelog
  remotes/upstream/set-release           d48ffe8 if not set, set the build type to Release
  remotes/upstream/switch-to-kscreen     85e49e5 Set mode at session start. Save settings in XDG_CONFIG_HOME (if exists)     or /.config/autostart.
  remotes/upstream/use-lxqt-build-tools  587e405 Use the new lxqt-build-tools package
  remotes/upstream/xdgicon_remove        ab87a68 all: Remove XdgIcon & XdgIconLoader usag
```
I guess that 47fb40f commit has to be the previous one in my master branch before my PR commit

So in master branch I rebase with upstream/master and use push --force

Hope I did it well, and thank you for your help.

**Comment by pmattern** [comment]
> I guess that 47fb40f commit has to be the previous one in my master branch before my PR commit

Right.

> Hope I did it well

Yes. The commit corresponding with this PR is now exactly placed like it should be.

The only thing that maybe still should be improved is the commit message which is a bit too verbose and factually not quite right (a TS file removal doesn't exist any more).
So sitting in branch master at commit 1467793f you may invoke `git commit --amend`, in the editor that comes up delete everything behind below the first line "Desktop entry files: [...]" as this is actually telling it all and run `git push --force` as usual.

**Comment by ioO** [comment]
Done :)

**Pull request merged**
