### PR TITLE
german translations for lxqt-config and modules

### PR DESCRIPTION
**Pull request by JoernSchoenyan**
please merge my german translations

### CODE REVIEW

**Comment by jleclanche** [comment]
@JoernSchoenyan This isn't mergeable on master, can you rebase/fix it please? it looks like you worked off an old version or something.

**Comment by jleclanche** [comment]
@JoernSchoenyan We're releasing soon, if you want this in 0.9 you'll have to take care of it asap :)

**Comment by JoernSchoenyan** [comment]
Honestly, Git, Bzr and all that stuff is my nemesis and I don't have any clue how that works.

**Comment by jleclanche** [comment]
Ok, I'll try to take care of it.

**Comment by jleclanche** [comment]
Superceded by #24

**Pull request closed without merging**
