### PR TITLE
Update lxqt-config-input.ts

### PR DESCRIPTION
**Pull request by stefonarch**
Removed &amp; in "Add" and "Remove", because creates #_Add #_Remove in Gui

### CODE REVIEW

**Comment by jleclanche** [comment]
These are access keys, but I'm not sure why it would look like that on your setup. It looks fine on mine.

**Comment by stefonarch** [comment]
I admit I ahve no idea what access keys means, but it looks liker that
(also in digikam I noticed the same thing).

Il 25/01/2015 15:51, Jerome Leclanche ha scritto:
> These are access keys, but I'm not sure why it would look like that on
> your setup. It looks fine on mine.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lxde/lxqt-config/pull/29#issuecomment-71375846>.
> 

-- 
********************************
Stef Binde
via della pieve 2
I-56024 Corazzano PI

Tel: ++39 0571 17 30 104
PGP: 0x728D9707

stef.binde@riseup.net
*******************************

**Comment by jleclanche** [comment]
Access keys are when you press alt+key to select an item with the keyboard. They are an accessibility feature.

**Comment by stefonarch** [comment]
Ok, got it.
So if I see them in source I let  them in the italian translation even
if it looks weird here?

Il 25/01/2015 18:02, Jerome Leclanche ha scritto:

**Pull request closed without merging**
