### PR TITLE
Add Qt5XdgIconLoader as dependency

### PR DESCRIPTION
**Pull request by jubalh**
Used in lxqt-config-appearance/iconthemeinfo.cpp.

### CODE REVIEW

**Comment by palinek** [comment]
Actually here I believe that the XdgIconLoader shouldn't be used any more. As the engine is used in regular QIcon calls (thanks to lxqt-qtplugin). I'll make the PR for the removal.

**Comment by jubalh** [comment]
Alright, feel free to close this issue when finished.

**Comment by palinek** [comment]
Done... please check, if the #102 fixes your build problems... and brings no new issues.

**Comment by jubalh** [comment]
Looks fine.

**Pull request closed without merging**
